# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

class Action(object):
    NONE = 0
    CatFeed = 1
    RatAttack = 2
    RatNap = 3
    RatCollision = 4
    PlaceDirt = 5
    BreakDirt = 6
    CheesePickup = 7
    CheeseSpawn = 8
    CatScratch = 9
    CatPounce = 10
    PlaceRatTrap = 11
    PlaceCatTrap = 12
    TriggerRatTrap = 13
    TriggerCatTrap = 14
    DamageAction = 15
    SpawnAction = 16
    DieAction = 17
    IndicatorStringAction = 18
    IndicatorDotAction = 19
    IndicatorLineAction = 20
