// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { BreakDirt } from '../../battlecode/schema/break-dirt';
import { CatFeed } from '../../battlecode/schema/cat-feed';
import { CatPounce } from '../../battlecode/schema/cat-pounce';
import { CatScratch } from '../../battlecode/schema/cat-scratch';
import { CheesePickup } from '../../battlecode/schema/cheese-pickup';
import { CheeseSpawn } from '../../battlecode/schema/cheese-spawn';
import { DamageAction } from '../../battlecode/schema/damage-action';
import { DieAction } from '../../battlecode/schema/die-action';
import { IndicatorDotAction } from '../../battlecode/schema/indicator-dot-action';
import { IndicatorLineAction } from '../../battlecode/schema/indicator-line-action';
import { IndicatorStringAction } from '../../battlecode/schema/indicator-string-action';
import { PlaceCatTrap } from '../../battlecode/schema/place-cat-trap';
import { PlaceDirt } from '../../battlecode/schema/place-dirt';
import { PlaceRatTrap } from '../../battlecode/schema/place-rat-trap';
import { RatAttack } from '../../battlecode/schema/rat-attack';
import { RatCollision } from '../../battlecode/schema/rat-collision';
import { RatNap } from '../../battlecode/schema/rat-nap';
import { SpawnAction } from '../../battlecode/schema/spawn-action';
import { TriggerCatTrap } from '../../battlecode/schema/trigger-cat-trap';
import { TriggerRatTrap } from '../../battlecode/schema/trigger-rat-trap';


export enum Action {
  NONE = 0,
  CatFeed = 1,
  RatAttack = 2,
  RatNap = 3,
  RatCollision = 4,
  PlaceDirt = 5,
  BreakDirt = 6,
  CheesePickup = 7,
  CheeseSpawn = 8,
  CatScratch = 9,
  CatPounce = 10,
  PlaceRatTrap = 11,
  PlaceCatTrap = 12,
  TriggerRatTrap = 13,
  TriggerCatTrap = 14,
  DamageAction = 15,
  SpawnAction = 16,
  DieAction = 17,
  IndicatorStringAction = 18,
  IndicatorDotAction = 19,
  IndicatorLineAction = 20
}

export function unionToAction(
  type: Action,
  accessor: (obj:BreakDirt|CatFeed|CatPounce|CatScratch|CheesePickup|CheeseSpawn|DamageAction|DieAction|IndicatorDotAction|IndicatorLineAction|IndicatorStringAction|PlaceCatTrap|PlaceDirt|PlaceRatTrap|RatAttack|RatCollision|RatNap|SpawnAction|TriggerCatTrap|TriggerRatTrap) => BreakDirt|CatFeed|CatPounce|CatScratch|CheesePickup|CheeseSpawn|DamageAction|DieAction|IndicatorDotAction|IndicatorLineAction|IndicatorStringAction|PlaceCatTrap|PlaceDirt|PlaceRatTrap|RatAttack|RatCollision|RatNap|SpawnAction|TriggerCatTrap|TriggerRatTrap|null
): BreakDirt|CatFeed|CatPounce|CatScratch|CheesePickup|CheeseSpawn|DamageAction|DieAction|IndicatorDotAction|IndicatorLineAction|IndicatorStringAction|PlaceCatTrap|PlaceDirt|PlaceRatTrap|RatAttack|RatCollision|RatNap|SpawnAction|TriggerCatTrap|TriggerRatTrap|null {
  switch(Action[type]) {
    case 'NONE': return null; 
    case 'CatFeed': return accessor(new CatFeed())! as CatFeed;
    case 'RatAttack': return accessor(new RatAttack())! as RatAttack;
    case 'RatNap': return accessor(new RatNap())! as RatNap;
    case 'RatCollision': return accessor(new RatCollision())! as RatCollision;
    case 'PlaceDirt': return accessor(new PlaceDirt())! as PlaceDirt;
    case 'BreakDirt': return accessor(new BreakDirt())! as BreakDirt;
    case 'CheesePickup': return accessor(new CheesePickup())! as CheesePickup;
    case 'CheeseSpawn': return accessor(new CheeseSpawn())! as CheeseSpawn;
    case 'CatScratch': return accessor(new CatScratch())! as CatScratch;
    case 'CatPounce': return accessor(new CatPounce())! as CatPounce;
    case 'PlaceRatTrap': return accessor(new PlaceRatTrap())! as PlaceRatTrap;
    case 'PlaceCatTrap': return accessor(new PlaceCatTrap())! as PlaceCatTrap;
    case 'TriggerRatTrap': return accessor(new TriggerRatTrap())! as TriggerRatTrap;
    case 'TriggerCatTrap': return accessor(new TriggerCatTrap())! as TriggerCatTrap;
    case 'DamageAction': return accessor(new DamageAction())! as DamageAction;
    case 'SpawnAction': return accessor(new SpawnAction())! as SpawnAction;
    case 'DieAction': return accessor(new DieAction())! as DieAction;
    case 'IndicatorStringAction': return accessor(new IndicatorStringAction())! as IndicatorStringAction;
    case 'IndicatorDotAction': return accessor(new IndicatorDotAction())! as IndicatorDotAction;
    case 'IndicatorLineAction': return accessor(new IndicatorLineAction())! as IndicatorLineAction;
    default: return null;
  }
}

export function unionListToAction(
  type: Action, 
  accessor: (index: number, obj:BreakDirt|CatFeed|CatPounce|CatScratch|CheesePickup|CheeseSpawn|DamageAction|DieAction|IndicatorDotAction|IndicatorLineAction|IndicatorStringAction|PlaceCatTrap|PlaceDirt|PlaceRatTrap|RatAttack|RatCollision|RatNap|SpawnAction|TriggerCatTrap|TriggerRatTrap) => BreakDirt|CatFeed|CatPounce|CatScratch|CheesePickup|CheeseSpawn|DamageAction|DieAction|IndicatorDotAction|IndicatorLineAction|IndicatorStringAction|PlaceCatTrap|PlaceDirt|PlaceRatTrap|RatAttack|RatCollision|RatNap|SpawnAction|TriggerCatTrap|TriggerRatTrap|null, 
  index: number
): BreakDirt|CatFeed|CatPounce|CatScratch|CheesePickup|CheeseSpawn|DamageAction|DieAction|IndicatorDotAction|IndicatorLineAction|IndicatorStringAction|PlaceCatTrap|PlaceDirt|PlaceRatTrap|RatAttack|RatCollision|RatNap|SpawnAction|TriggerCatTrap|TriggerRatTrap|null {
  switch(Action[type]) {
    case 'NONE': return null; 
    case 'CatFeed': return accessor(index, new CatFeed())! as CatFeed;
    case 'RatAttack': return accessor(index, new RatAttack())! as RatAttack;
    case 'RatNap': return accessor(index, new RatNap())! as RatNap;
    case 'RatCollision': return accessor(index, new RatCollision())! as RatCollision;
    case 'PlaceDirt': return accessor(index, new PlaceDirt())! as PlaceDirt;
    case 'BreakDirt': return accessor(index, new BreakDirt())! as BreakDirt;
    case 'CheesePickup': return accessor(index, new CheesePickup())! as CheesePickup;
    case 'CheeseSpawn': return accessor(index, new CheeseSpawn())! as CheeseSpawn;
    case 'CatScratch': return accessor(index, new CatScratch())! as CatScratch;
    case 'CatPounce': return accessor(index, new CatPounce())! as CatPounce;
    case 'PlaceRatTrap': return accessor(index, new PlaceRatTrap())! as PlaceRatTrap;
    case 'PlaceCatTrap': return accessor(index, new PlaceCatTrap())! as PlaceCatTrap;
    case 'TriggerRatTrap': return accessor(index, new TriggerRatTrap())! as TriggerRatTrap;
    case 'TriggerCatTrap': return accessor(index, new TriggerCatTrap())! as TriggerCatTrap;
    case 'DamageAction': return accessor(index, new DamageAction())! as DamageAction;
    case 'SpawnAction': return accessor(index, new SpawnAction())! as SpawnAction;
    case 'DieAction': return accessor(index, new DieAction())! as DieAction;
    case 'IndicatorStringAction': return accessor(index, new IndicatorStringAction())! as IndicatorStringAction;
    case 'IndicatorDotAction': return accessor(index, new IndicatorDotAction())! as IndicatorDotAction;
    case 'IndicatorLineAction': return accessor(index, new IndicatorLineAction())! as IndicatorLineAction;
    default: return null;
  }
}
