// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

@SuppressWarnings("unused")
public final class Action {
  private Action() { }
  public static final byte NONE = 0;
  public static final byte CatFeed = 1;
  public static final byte RatAttack = 2;
  public static final byte RatNap = 3;
  public static final byte RatCollision = 4;
  public static final byte PlaceDirt = 5;
  public static final byte BreakDirt = 6;
  public static final byte CheesePickup = 7;
  public static final byte CheeseSpawn = 8;
  public static final byte CatScratch = 9;
  public static final byte CatPounce = 10;
  public static final byte PlaceRatTrap = 11;
  public static final byte PlaceCatTrap = 12;
  public static final byte TriggerRatTrap = 13;
  public static final byte TriggerCatTrap = 14;
  public static final byte DamageAction = 15;
  public static final byte SpawnAction = 16;
  public static final byte DieAction = 17;
  public static final byte IndicatorStringAction = 18;
  public static final byte IndicatorDotAction = 19;
  public static final byte IndicatorLineAction = 20;

  public static final String[] names = { "NONE", "CatFeed", "RatAttack", "RatNap", "RatCollision", "PlaceDirt", "BreakDirt", "CheesePickup", "CheeseSpawn", "CatScratch", "CatPounce", "PlaceRatTrap", "PlaceCatTrap", "TriggerRatTrap", "TriggerCatTrap", "DamageAction", "SpawnAction", "DieAction", "IndicatorStringAction", "IndicatorDotAction", "IndicatorLineAction", };

  public static String name(int e) { return names[e]; }
}

